# Generated by Django 5.0.3 on 2024-04-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=225)),
                ('student_attendence', models.IntegerField()),
                ('student_Email', models.EmailField(max_length=33)),
                ('student_contactNo', models.IntegerField()),
            ],
            options={
                'db_table': 'Personal_details',
            },
        ),
    ]
