# Generated by Django 5.0.3 on 2024-04-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailapp', '0002_alter_details_student_attendence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='student_contactNo',
            field=models.IntegerField(null=True),
        ),
    ]
