# Generated by Django 5.0.3 on 2024-04-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=225)),
                ('student_attendence', models.IntegerField()),
                ('student_Email', models.EmailField(max_length=33)),
                ('student_contactNo', models.IntegerField()),
                ('Student_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20, null=True)),
                ('student_Course', models.CharField(choices=[('Java', 'Java'), ('Python', 'Python')], max_length=10, null=True)),
                ('student_photo', models.ImageField(upload_to='')),
                ('student_assignment', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'student_db',
            },
        ),
    ]
